### ISSUE TITLE
CC license selection and navigation: Bird's eye view version

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/cc-usability-prototypes#1]
UCB student Conner:

- Persona, sketch file, and design system are located in this [Google Folder](https://drive.google.com/open?id=1NKxTL2NDBRmXxqzPkO3O6HbVROnYQSLC).
- The [mobile prototype](https://invis.io/UXPB3TCANGB) on Invision 
- The [desktop prototype](https://invis.io/FTPCKYLQVWY) on Invision
- The demo for the [Google Slides plugin](https://www.youtube.com/watch?v=FRtFQnNJARk&feature=youtu.be) on YouTube

[My initial feedback](https://docs.google.com/document/d/13WBvVeEImrGk5aB4HDJYv-Co_efZlisWHhMo7TTnkgY/edit)

**Comment by rakaar** [comment]
I would like to work on this. Can I get the source code of the desktop prototype version so that I can work over it ?

**Comment by kgodey** [comment]
There's no source code yet, this is just a design/concept that needs to be built from scratch. All available files are in Jane's link to the Google Folder.

**Comment by akmadian** [comment]
Commenting for reference
