### ISSUE TITLE
CC license selection and navigation: Creator-specific

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/cc-usability-prototypes#2]
UCB student Claire:
- [Project Presentation on Google slides](https://docs.google.com/presentation/d/15yoiIY3j3rDkeqecoDnSgJ-VE7OiqurK1iqSfsoxiiI/edit?usp=sharing)
- [Figma Board + Design System](https://www.figma.com/file/BOdtIkXh65XCksKr32ZZHcgE/Creative-Commons-Licensing-Project?node-id=0%3A1) 

[My initial feedback](https://docs.google.com/document/d/10bFzz3W0Lu1T9cEZKeii6euLovTBlFFzOm5IoLtGPdw/edit)

**Comment by akmadian** [comment]
Commenting for reference

**Comment by possumbilities** [comment]
Closing. This repository will soon be archived.
