### ISSUE TITLE
CC archive concept tied to CC site license selection

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/cc-usability-prototypes#3]
UCB student Rebecca:
- [Presentation slide deck ](https://docs.google.com/presentation/d/1OCKEXERT0mqoW9sFUMiBykqTe68CFGFyeWPTm_OhTg8/edit?usp=sharing)
- [Figma](https://www.figma.com/file/0z4BgXS0Jspgvl3eVzgR44g7/CC-Archive?node-id=83%3A101)
- [Invision](https://invis.io/2SPCRCDJFB7)

[My initial feedback](https://docs.google.com/document/d/1WgNAmG5UwKkguyOMeZcl9bOq-dJXbb0MtoKrYhOAsXk/edit)

**Comment by rebeccayeap** [comment]
Updated Invision Link with New Iteration: https://projects.invisionapp.com/share/5DQS1AD2BQC#/349852668_Google_Chrome_Extension_Store

**Comment by possumbilities** [comment]
Closing. This repository will soon be archived.
