### ISSUE TITLE
CC archive concept embedded in platforms

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/cc-usability-prototypes#4]
UCB student Paul:
- [Google drive](https://drive.google.com/drive/folders/17hpbbAfp9qqjf2PGCwIbcw0SdSP2zurx?usp=sharing)

[My initial feedback](https://docs.google.com/document/d/1XQcdBAppNMZRyIUPEyDX2R1OHwDf6AHarvysNPXbkc0/edit)

**Comment by possumbilities** [comment]
Closing. This repository will soon be archived.
