### ISSUE TITLE
CC ID concept

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/cc-usability-prototypes#5]
UCB student Emilio:
- [Figma](https://www.figma.com/file/BXbjdiB2dxP2YwlkOECswfSZ/Creative-Commons-Reward-and-Delight?node-id=0%3A1)

[My initial feedback](https://docs.google.com/document/d/1oDHGy5KkR2ns8vVupWADsStb-6NH50aHuA6TY3wOlJc/edit)

**Comment by possumbilities** [comment]
Closing. This repository will soon be archived.
